[package]
name = "degenerate"
version = "0.0.0"
description = "Raw Degeneracy"
edition = "2021"
license = "CC0-1.0"
autotests = false

[dependencies]
dirs = "4.0.0"
image = "0.23.14"
nalgebra = "0.29.0"
num-traits = "0.2.14"
rand = "0.8.4"
rand_derive2 = "0.1.17"
rustyline = "9.1.1"
strum = { version = "0.23.0", features = ["derive"] }

[dev-dependencies]
executable-path = "1.0.0"
pretty_assertions = "1.0.0"
tempfile = "3.2.0"
unindent = "0.1.7"

[[test]]
name = "integration"
path = "tests/integration.rs"
