[package]
name = "degenerate"
version = "0.0.0"
description = "Raw Degeneracy"
edition = "2021"
license = "CC0-1.0"

[dependencies]
image = "0.23.14"
structopt = "0.3.25"

[dev-dependencies]
executable-path = "1.0.0"
