[package]
name = "serve"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.5.6"
ctrlc = "3.2.2"
tokio = { version = "1.18.2", features = ["macros", "rt", "rt-multi-thread"] }
tower-http = { version = "0.3.0", features = ["fs", "trace", "set-header"] }
tracing-subscriber = { version = "0.3.0", features = ["env-filter"] }
