name: Pages

on:
  push:
    branches:
    - build-pages

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust Toolchain Components
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build Pages
      run: cargo run --package build-pages

    - name: Upload Pages
      run: ./bin/upload-pages
